Following the keras introduction tutorial : https://keras.io/getting_started/intro_to_keras_for_researchers/#keeping-track-of-training-metrics

In [1]:
# importing libraries

In [2]:
import tensorflow as tf
from tensorflow import keras

In [3]:
# creating a constant tensor
x = tf.constant([[5,2], [1,3]])
print(x)

tf.Tensor(
[[5 2]
 [1 3]], shape=(2, 2), dtype=int32)


In [4]:
# converting a tensor to numpy array
x.numpy()

array([[5, 2],
       [1, 3]], dtype=int32)

In [5]:
# checking the dtype and shape of the tensor
print("dtype:", x.dtype)
print("shape:", x.shape)

dtype: <dtype: 'int32'>
shape: (2, 2)


In [6]:
# creating constant tensors using tf.ones and tf.zeros method
# the method is similar to numpy methods (np.ones & np.zeros)
print(tf.ones(shape=(2,1)))
print(tf.zeros(shape=(2,1)))

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [7]:
# creating random constant tensors
x = tf.random.normal(shape=(2,2), mean=0.0, stddev=1.0)
x = tf.random.uniform(shape=(2,2), minval=0, maxval=10, dtype="int32")

In [10]:
# creating a variable using initial value
initial_value__of_variable = tf.random.normal(shape=(2,2))
a_random_variable = tf.Variable(initial_value__of_variable)
print(a_random_variable)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.14770553,  0.9771248 ],
       [-2.6789577 ,  0.9209706 ]], dtype=float32)>


In [19]:
#updating the value of the variable using the methods .assign(value), .assign_add(increment), or.assign_sub_(decrement)
new_value_to_update = tf.random.normal(shape=(2,2)) 
a_random_variable.assign(new_value_to_update) 
for i in range(2): 
  for j in range(2): 
      assert a_random_variable[i,j] == new_value_to_update[i,j]

added_value = tf.random.normal(shape=(2,2)) 
a_random_variable.assign_add(added_value) 
for i in range(2): 
  for j in range(2): 
    assert a_random_variable[i,j] == new_value_to_update[i, j] + added_value[i, j]

In [21]:
# math operations in tensorflow
z = tf.random.normal(shape=(2,2))
x = tf.random.normal(shape=(2,2))
y = z + x
o = tf.square(y)
p = tf.exp(o)

In [22]:
# gradients 
# you can retrive the gradient of any differentiable expression
# just open the gradient tape, start watching a tensor via tape.watch(), and compose a differentiable expression using this tensor as input
with tf.GradientTape() as tape:
  # record the operations history of tensor z 
  tape.watch(z) 
  a = tf.sqrt(tf.square(z) + tf.square(y))
  # gradient of a with respect to z
  da_dz = tape.gradient(a,z)
  print(da_dz)
  

tf.Tensor(
[[ 0.9105888   0.49310702]
 [ 0.25751022 -0.14513414]], shape=(2, 2), dtype=float32)
